Repository kyranet/drakhtar, pull requests merged in 2019-04, with the labels that each got.

#65 Recruitment scene
  Drakhtar/EventListeners/UnitStoreController.cpp
  Drakhtar/EventListeners/UnitStoreController.h
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/Managers/PlayerData.cpp
  Drakhtar/Managers/PlayerData.h
  Drakhtar/Scenes/MenuScene.cpp
  Drakhtar/Scenes/RecruitScene.cpp
  Drakhtar/Scenes/RecruitScene.h
  Drakhtar/Structures/Game.cpp
  Drakhtar/main.cpp
Labels: enhancement

#74 Recruitment system completed
  Drakhtar/EventListeners/BoardController.cpp
  Drakhtar/EventListeners/UnitStoreController.cpp
  Drakhtar/GameObjects/Battalion.cpp
  Drakhtar/GameObjects/Battalion.h
  Drakhtar/GameObjects/Commanders/Commander.cpp
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/GameObjects/Unit.h
  Drakhtar/Managers/GameManager.cpp
  Drakhtar/Managers/GameManager.h
  Drakhtar/Managers/PlayerData.cpp
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/RecruitScene.cpp
  Drakhtar/Structures/UnitFactory.cpp
  Drakhtar/main.cpp
Labels: enhancement

#77 misc: Change static casts to reinterpret casts where actually required
  Drakhtar/EventListeners/UnitStoreController.cpp
  Drakhtar/GameObjects/Board.cpp
  Drakhtar/GameObjects/DialogScene.cpp
  Drakhtar/GameObjects/TutorialSequence.cpp
  Drakhtar/Structures/Tween.cpp
Labels: enhancement

#82 misc: Fixed MSVC's faulty code for cross-platform compatibility
  .gitignore
  CMakeLists.txt
  Drakhtar/EventListeners/BoardController.cpp
  Drakhtar/GameObjects/DialogScene.cpp
  Drakhtar/GameObjects/DialogScene.h
  Drakhtar/GameObjects/GameObject.cpp
  Drakhtar/GameObjects/GameObject.h
  Drakhtar/GameObjects/SkilButton.cpp
  Drakhtar/GameObjects/Skill.cpp
  Drakhtar/GameObjects/Text.cpp
  Drakhtar/GameObjects/TurnBar.cpp
  Drakhtar/GameObjects/TutorialSequence.cpp
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/GameObjects/Unit.h
  Drakhtar/Managers/FontManager.h
  Drakhtar/Managers/Input.cpp
  Drakhtar/Structures/Team.cpp
  Drakhtar/Structures/Texture.cpp
  Drakhtar/Structures/Texture.h
  Drakhtar/Structures/Tween.cpp
  Drakhtar/Utils/Vector2D.h
  Drakhtar/main.cpp
  Drakhtar/third_party/AStar.cpp
  Makefile
  README.md
  azure-pipelines.yml
  cmake/FindSDL2_image.cmake
  cmake/FindSDL2_mixer.cmake
Labels: m: enhancement, t: build, t: ci

#84 fix: Keyboard keys being slightly incorrect
  Drakhtar/Utils/Constants.h
Labels: t: bugfix

#73 feat: ScreenPointToRay and EE refactor
  .clang-format
  CMakeLists.txt
  Drakhtar/EventListeners/BoardController.cpp
  Drakhtar/EventListeners/BoardController.h
  Drakhtar/EventListeners/DialogSceneOnClick.cpp
  Drakhtar/EventListeners/DialogSceneOnClick.h
  Drakhtar/EventListeners/EventListener.cpp
  Drakhtar/EventListeners/EventListener.h
  Drakhtar/EventListeners/ListenerOnClick.cpp
  Drakhtar/EventListeners/ListenerOnClick.h
  Drakhtar/EventListeners/TutorialSceneOnClick.cpp
  Drakhtar/EventListeners/TutorialSceneOnClick.h
  Drakhtar/EventListeners/UnitStoreController.cpp
  Drakhtar/EventListeners/UnitStoreController.h
  Drakhtar/GameObjects/Base/Sequence.cpp
  Drakhtar/GameObjects/Base/Sequence.h
  Drakhtar/GameObjects/Board.cpp
  Drakhtar/GameObjects/Board.h
  Drakhtar/GameObjects/Button.cpp
  Drakhtar/GameObjects/Button.h
  Drakhtar/GameObjects/DialogScene.cpp
  Drakhtar/GameObjects/DialogScene.h
  Drakhtar/GameObjects/GameObject.cpp
  Drakhtar/GameObjects/GameObject.h
  Drakhtar/GameObjects/TutorialBox.h
  Drakhtar/GameObjects/TutorialSequence.cpp
  Drakhtar/GameObjects/TutorialSequence.h
  Drakhtar/Managers/Input.cpp
  Drakhtar/Managers/Input.h
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/GameScene.h
  Drakhtar/Scenes/Scene.cpp
  Drakhtar/Scenes/Scene.h
  Drakhtar/main.cpp
Labels: m: enhancement, t: feature

#86 ci: Boosted build time by using all cores
  Makefile
  azure-pipelines.yml
Labels: t: build, t: ci

#87 refactor: Make all EventLoop exits "soft"
  Drakhtar/GameObjects/DialogScene.cpp
  Drakhtar/GameObjects/Pause.cpp
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/GameScene.h
  Drakhtar/Scenes/MenuScene.cpp
  Drakhtar/Scenes/RecruitScene.cpp
  Drakhtar/Scenes/Scene.cpp
  Drakhtar/Scenes/Scene.h
  Drakhtar/Structures/SceneMachine.cpp
Labels: m: enhancement

#83 feat: Health bar
  Drakhtar/GameObjects/Battalion.cpp
  Drakhtar/GameObjects/Battalion.h
  Drakhtar/GameObjects/Box.cpp
  Drakhtar/GameObjects/Commanders/Commander.cpp
  Drakhtar/GameObjects/Commanders/Commander.h
  Drakhtar/GameObjects/HealthBar.cpp
  Drakhtar/GameObjects/HealthBar.h
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/GameObjects/Unit.h
  Drakhtar/Structures/Game.cpp
  images/UI/goldskull.png
  images/UI/healthBar_background.png
  images/UI/healthBar_damage.png
  images/UI/healthBar_life.png
Labels: t: feature

#88 GameScene can be used for any level
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/GameScene.h
  levels/level-1.txt
Labels: m: enhancement

#79 TeamController
  Drakhtar/Controllers/AIController.cpp
  Drakhtar/Controllers/AIController.h
  Drakhtar/Controllers/PlayerController.cpp
  Drakhtar/Controllers/PlayerController.h
  Drakhtar/Controllers/UnitStoreController.cpp
  Drakhtar/Controllers/UnitStoreController.h
  Drakhtar/Controllers/UnitsController.cpp
  Drakhtar/Controllers/UnitsController.h
  Drakhtar/EventListeners/EventListener.cpp
  Drakhtar/EventListeners/EventListener.h
  Drakhtar/EventListeners/ListenerOnClick.cpp
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/GameScene.h
  Drakhtar/Scenes/RecruitScene.cpp
Labels: m: enhancement, t: feature

#81 Tutorial fix
  Drakhtar/GameObjects/Dialog.cpp
  Drakhtar/GameObjects/TutorialBox.cpp
  Drakhtar/GameObjects/TutorialBox.h
  Drakhtar/GameObjects/TutorialSequence.cpp
  Drakhtar/Structures/Game.cpp
  images/Tutorials/tutorial_1.png
  images/Tutorials/tutorial_2.PNG
  images/Tutorials/tutorial_3.PNG
  images/Tutorials/tutorial_4.PNG
  images/Tutorials/tutorial_5.PNG
  images/Tutorials/tutorial_6.png
  images/Tutorials/tutorial_7.PNG
  images/Tutorials/tutorial_8.PNG
  images/Tutorials/tutorial_9.PNG
  images/Tutorials/tutorial_Box.png
  images/UI/tutorialBackground.png
  tutorials/tutorials.txt
Labels: t: bugfix

#89 legal: Added MIT LICENSE
  LICENSE
Labels: t: legal

#91 ResizedImages&BetaWalkAnimations
  Drakhtar/Controllers/PlayerController.cpp
  Drakhtar/Controllers/UnitsController.h
  Drakhtar/Managers/TextureManager.cpp
  Drakhtar/Managers/TextureManager.h
  Drakhtar/Structures/Game.cpp
  Drakhtar/Structures/Texture.cpp
  Drakhtar/Structures/Texture.h
  Drakhtar/Structures/Tween.cpp
  images/Units/Abeizhul.png
  images/Units/BlueArcher.png
  images/Units/BlueKnight.png
  images/Units/BlueMage.png
  images/Units/BlueMonster.png
  images/Units/BlueSoldier.png
  images/Units/BlueValar.png
  images/Units/Dreilay.png
  images/Units/RedArcher.png
  images/Units/RedKnight.png
  images/Units/RedMage.png
  images/Units/RedMonster.png
  images/Units/RedSoldier.png
  images/Units/RedValar.png
  images/Units/Sheissa.png
  images/Units/Thassa.png
  images/Units/Valar.png
Labels: m: enhancement

#97 refactor: Reworked Team, Unit, and TurnBar
  Drakhtar/Controllers/AIController.cpp
  Drakhtar/Controllers/PlayerController.cpp
  Drakhtar/Controllers/UnitsController.cpp
  Drakhtar/GameObjects/GameObject.cpp
  Drakhtar/GameObjects/GameObject.h
  Drakhtar/GameObjects/Skill.cpp
  Drakhtar/GameObjects/TurnBar.cpp
  Drakhtar/GameObjects/TurnBar.h
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/GameObjects/Unit.h
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/GameScene.h
  Drakhtar/Structures/Team.cpp
  Drakhtar/Structures/Team.h
  Drakhtar/Structures/UnitFactory.cpp
Labels: m: enhancement, t: bugfix

#101 misc: Reworked Controllers
  Drakhtar/Controllers/AIController.cpp
  Drakhtar/Controllers/AIController.h
  Drakhtar/Controllers/Handlers/PlayerHandler.cpp
  Drakhtar/Controllers/Handlers/PlayerHandler.h
  Drakhtar/Controllers/PlayerController.cpp
  Drakhtar/Controllers/PlayerController.h
  Drakhtar/Controllers/UnitsController.cpp
  Drakhtar/Controllers/UnitsController.h
  Drakhtar/GameObjects/Box.cpp
  Drakhtar/GameObjects/Box.h
  Drakhtar/GameObjects/TurnBar.cpp
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/GameScene.h
  Drakhtar/Structures/Team.cpp
  Drakhtar/Structures/Team.h
Labels: m: enhancement, t: bugfix

#103 feat(Assets): More animations, re-added BlueValar
  Drakhtar/Structures/Game.cpp
  images/Units/Abeizhul.png
  images/Units/BlueValar.png
  images/Units/Thassa.png
  images/Units/Zamdran.png
Labels: m: art, m: enhancement

#85 Unit stat pop up in recruitment
  Drakhtar/Controllers/UnitStoreController.cpp
  Drakhtar/Controllers/UnitStoreController.h
  Drakhtar/EventListeners/ListenerOnHover.cpp
  Drakhtar/EventListeners/ListenerOnHover.h
  Drakhtar/EventListeners/StoreListener.cpp
  Drakhtar/EventListeners/StoreListener.h
  Drakhtar/GameObjects/Battalion.cpp
  Drakhtar/GameObjects/RecruitmentStat.cpp
  Drakhtar/GameObjects/RecruitmentStat.h
  Drakhtar/Managers/GameManager.cpp
  Drakhtar/Managers/GameManager.h
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/MenuScene.cpp
  Drakhtar/Scenes/RecruitScene.cpp
  Drakhtar/Scenes/RecruitScene.h
  Drakhtar/Scenes/Scene.cpp
  Drakhtar/Structures/Game.cpp
  Drakhtar/Structures/UnitFactory.cpp
  Drakhtar/Structures/UnitFactory.h
Labels: t: feature

#95 Commander death
  Drakhtar/GameObjects/Commanders/Commander.cpp
  Drakhtar/GameObjects/Commanders/Commander.h
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/GameScene.h
  Drakhtar/Scenes/TransitionScene.cpp
  Drakhtar/Scenes/TransitionScene.h
Labels: m: enhancement, t: feature

#107 refactor(Button): Simplified code
  Drakhtar/EventListeners/ButtonListener.cpp
  Drakhtar/EventListeners/ButtonListener.h
  Drakhtar/GameObjects/Button.cpp
  Drakhtar/GameObjects/Button.h
  Drakhtar/GameObjects/ButtonText.cpp
  Drakhtar/GameObjects/ButtonText.h
Labels: m: enhancement, t: bugfix

#108 fix: Resolved all "click blinds".
  Drakhtar/Controllers/Handlers/PlayerHandler.cpp
  Drakhtar/GameObjects/TurnBar.cpp
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/Scenes/GameScene.cpp
Labels: m: enhancement, t: bugfix

#100 feat: Multiple sprites in a battalion
  Drakhtar/GameObjects/Battalion.cpp
  Drakhtar/GameObjects/Battalion.h
  Drakhtar/GameObjects/Commanders/Commander.cpp
  Drakhtar/GameObjects/Commanders/Commander.h
  Drakhtar/GameObjects/Unit.cpp
Labels: m: enhancement, t: feature

#109 abstraction in everything about unit creation and fixed stat-related bugs
  Drakhtar/Controllers/PlayerController.cpp
  Drakhtar/GameObjects/Battalion.cpp
  Drakhtar/GameObjects/Battalion.h
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/GameObjects/Unit.h
  Drakhtar/Managers/GameManager.cpp
  Drakhtar/Managers/GameManager.h
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Structures/UnitFactory.cpp
  Drakhtar/Structures/UnitFactory.h
  levels/level-1.txt
Labels: m: enhancement, t: bugfix

#110 TurnManager and turn order fix
  Drakhtar/Controllers/AIController.cpp
  Drakhtar/Controllers/AIController.h
  Drakhtar/Controllers/PlayerController.cpp
  Drakhtar/Controllers/PlayerController.h
  Drakhtar/Controllers/UnitsController.cpp
  Drakhtar/Controllers/UnitsController.h
  Drakhtar/GameObjects/Box.cpp
  Drakhtar/GameObjects/TurnBar.cpp
  Drakhtar/GameObjects/TurnBar.h
  Drakhtar/Managers/TurnManager.cpp
  Drakhtar/Managers/TurnManager.h
  Drakhtar/Scenes/GameScene.cpp
Labels: m: enhancement, t: bugfix, t: feature

#98 Options Menu
  Drakhtar/Controllers/AIController.cpp
  Drakhtar/GameObjects/GameObject.cpp
  Drakhtar/GameObjects/GameObject.h
  Drakhtar/GameObjects/HealthBar.h
  Drakhtar/GameObjects/OptionsMenu.cpp
  Drakhtar/GameObjects/OptionsMenu.h
  Drakhtar/Managers/SDLAudioManager.cpp
  Drakhtar/Managers/SDLAudioManager.h
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/MenuScene.cpp
  Drakhtar/Structures/Game.cpp
  Drakhtar/Structures/Team.cpp
  images/UI/ActiveSound.png
  images/UI/MuteSound.png
  images/UI/OptionsMenu.png
  images/UI/WhiteBox.png
  images/UI/green-check.png
Labels: m: enhancement, t: feature

#112 GameManager resets and updates
  Drakhtar/GameObjects/Battalion.cpp
  Drakhtar/GameObjects/Commanders/Commander.cpp
  Drakhtar/GameObjects/Pause.cpp
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/Managers/GameManager.cpp
  Drakhtar/Managers/GameManager.h
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/GameScene.h
  Drakhtar/Scenes/RecruitScene.cpp
Labels: t: bugfix

#122 feat(Assets): Added walk and death animations
  Drakhtar/Controllers/PlayerController.cpp
  Drakhtar/Structures/Game.cpp
  images/Units/Abeizhul.png
  images/Units/BlueArcher.png
  images/Units/BlueKnight.png
  images/Units/BlueMage.png
  images/Units/BlueMonster.png
  images/Units/BlueSoldier.png
  images/Units/BlueValar.png
  images/Units/Dreilay.png
  images/Units/RedArcher.png
  images/Units/RedKnight.png
  images/Units/RedMage.png
  images/Units/RedMonster.png
  images/Units/RedSoldier.png
  images/Units/RedValar.png
  images/Units/Sheissah.png
  images/Units/Thassa.png
  images/Units/Zamdran.png
Labels: m: art, m: enhancement, t: feature

#120 fix: Resolved bug where the knight would move after finishing the tutorials
  Drakhtar/Controllers/UnitsController.cpp
  Drakhtar/EventListeners/ButtonListener.cpp
  Drakhtar/EventListeners/ButtonListener.h
  Drakhtar/GameObjects/DialogScene.cpp
  Drakhtar/GameObjects/TutorialSequence.cpp
  Drakhtar/Scenes/Scene.cpp
  Drakhtar/Scenes/Scene.h
Labels: t: bugfix
