Repository kyranet/drakhtar, pull requests merged in 2019-05, with the labels that each got.

#125 Stats as structs
  Drakhtar/GameObjects/Battalion.cpp
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/GameObjects/Unit.h
  Drakhtar/Structures/UnitFactory.cpp
  Drakhtar/Utils/Constants.h
Labels: m: enhancement, t: bugfix

#123 Thassa and archer counter fix
  Drakhtar/GameObjects/Commanders/Thassa.cpp
  Drakhtar/GameObjects/Unit.cpp
Labels: t: bugfix, t: feature

#126 Stats box
  Drakhtar/EventListeners/ListenerOnHover.h
  Drakhtar/EventListeners/StatBoxListener.cpp
  Drakhtar/EventListeners/StatBoxListener.h
  Drakhtar/GameObjects/Board.cpp
  Drakhtar/GameObjects/Skill.cpp
  Drakhtar/GameObjects/Text.cpp
  Drakhtar/GameObjects/Text.h
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/GameObjects/UnitDescriptionBox.cpp
  Drakhtar/GameObjects/UnitDescriptionBox.h
  Drakhtar/Managers/TurnManager.cpp
  Drakhtar/Managers/TurnManager.h
  Drakhtar/Scenes/GameScene.cpp
  images/Recruitment/reward_Panel.png
Labels: m: enhancement, t: bugfix, t: feature

#129 Adjust size units and maps. New Map
  Drakhtar/GameObjects/Commanders/Commander.cpp
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/Structures/Game.cpp
  images/Maps/FifthBattle.png
  images/Maps/FourthBattle.png
  images/Maps/SecondBattle.png
  images/Maps/ThirdBattle.png
Labels: m: art, t: feature

#132 Bugfix
  Drakhtar/Controllers/PlayerController.cpp
Labels: m: bug

#134 constant reference string parameters
  Drakhtar/EventListeners/StoreListener.cpp
  Drakhtar/EventListeners/StoreListener.h
  Drakhtar/GameObjects/Battalion.cpp
  Drakhtar/GameObjects/Battalion.h
  Drakhtar/GameObjects/ButtonText.cpp
  Drakhtar/GameObjects/ButtonText.h
  Drakhtar/GameObjects/Commanders/Commander.cpp
  Drakhtar/GameObjects/Commanders/Commander.h
  Drakhtar/GameObjects/Skill.cpp
  Drakhtar/GameObjects/Skill.h
  Drakhtar/GameObjects/Text.cpp
  Drakhtar/GameObjects/Text.h
  Drakhtar/Managers/AudioManager.h
  Drakhtar/Managers/SDLAudioManager.cpp
  Drakhtar/Managers/SDLAudioManager.h
  Drakhtar/Scenes/RecruitScene.cpp
  Drakhtar/Scenes/RecruitScene.h
Labels: m: enhancement

#137 Hover textures
  Drakhtar/GameObjects/Box.cpp
  Drakhtar/GameObjects/Box.h
  Drakhtar/Structures/Game.cpp
  images/UI/cellHoverBlue.png
  images/UI/cellHoverRed.png
Labels: m: enhancement, t: feature

#130 Tutorial whole rework
  .gitignore
  Drakhtar/Controllers/PlayerController.cpp
  Drakhtar/Controllers/PlayerController.h
  Drakhtar/EventListeners/TutorialSceneOnClick.cpp
  Drakhtar/EventListeners/TutorialSceneOnClick.h
  Drakhtar/GameObjects/DialogScene.cpp
  Drakhtar/GameObjects/GameOverPanel.cpp
  Drakhtar/GameObjects/TutorialBox.cpp
  Drakhtar/GameObjects/TutorialBox.h
  Drakhtar/GameObjects/TutorialSequence.cpp
  Drakhtar/GameObjects/TutorialSequence.h
  Drakhtar/GameObjects/TutorialText.cpp
  Drakhtar/GameObjects/TutorialText.h
  Drakhtar/Managers/GameManager.cpp
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/GameScene.h
  Drakhtar/Scenes/MenuScene.cpp
  Drakhtar/Scenes/RecruitScene.cpp
  Drakhtar/Scenes/RecruitScene.h
  Drakhtar/Scenes/Scene.cpp
  Drakhtar/Scenes/Scene.h
  Drakhtar/Structures/Game.cpp
  Drakhtar/Utils/Constants.h
  images/Tutorials/tutorial_.png
  images/UI/arrow_anim.png
  levels/level-1.txt
  tutorials/prueba.txt
  tutorials/tutorials.txt
Labels: m: enhancement, t: feature

#143 Quick fix master level crash
  Drakhtar/GameObjects/Commanders/Abeizhul.cpp
  Drakhtar/GameObjects/DialogScene.cpp
  Drakhtar/GameObjects/DialogScene.h
  Drakhtar/GameObjects/GameOverPanel.cpp
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Structures/Game.cpp
  dialog/dialog3.txt
  dialog/dialog4.txt
  dialog/dialog4transition.txt
  dialog/dialog5.txt
  dialog/dialog5transition.txt
  images/Transition/Transition_6.png
  levels/level-3.txt
  levels/level-4.txt
  levels/level-5.txt
  levels/level3.txt
Labels: m: enhancement, t: bugfix

#141 Abilities Animations + Obstacles
  Drakhtar/Structures/Game.cpp
  images/Obstacles/BottomTruck.png
  images/Obstacles/Box.png
  images/Obstacles/Fence.png
  images/Obstacles/Rock.png
  images/Obstacles/TopTruck.png
  images/Obstacles/Torch.png
  images/Obstacles/Trees.png
  images/Units/Abeizhul.png
  images/Units/Dreilay.png
  images/Units/RedValar.png
  images/Units/Sheissah.png
  images/Units/Thassa.png
  images/Units/Zamdran.png
Labels: m: art, m: enhancement, t: feature

#131 feat: Blue and red health bars and battalion number background sprite
  Drakhtar/GameObjects/Battalion.cpp
  Drakhtar/GameObjects/Battalion.h
  Drakhtar/GameObjects/Commanders/Commander.cpp
  Drakhtar/GameObjects/Commanders/Commander.h
  Drakhtar/GameObjects/HealthBar.cpp
  Drakhtar/GameObjects/HealthBar.h
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/GameObjects/Unit.h
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Structures/Game.cpp
  Drakhtar/Structures/Team.cpp
  Drakhtar/Structures/Texture.cpp
  Drakhtar/Structures/Texture.h
  images/UI/healthBar_blue.png
  images/UI/unitBatallionCircle.png
  images/UI/unitBatallionCircle2.png
Labels: m: enhancement

#138 fix: Resolved all build warnings
  CMakeLists.txt
  Drakhtar/Controllers/PlayerController.cpp
  Drakhtar/EventListeners/StoreListener.cpp
  Drakhtar/GameObjects/Board.cpp
  Drakhtar/GameObjects/Board.h
  Drakhtar/GameObjects/HealthBar.cpp
  Drakhtar/GameObjects/RecruitmentStat.cpp
  Drakhtar/GameObjects/Skill.cpp
  Drakhtar/GameObjects/Skill.h
  Drakhtar/GameObjects/SkillDescriptionBox.cpp
  Drakhtar/GameObjects/TurnBar.cpp
  Drakhtar/GameObjects/TutorialBox.cpp
  Drakhtar/GameObjects/TutorialText.cpp
  Drakhtar/GameObjects/TutorialText.h
  Drakhtar/GameObjects/UnitDescriptionBox.cpp
  Drakhtar/Managers/SDLAudioManager.cpp
  Drakhtar/Managers/SDLAudioManager.h
  Drakhtar/Managers/TextureManager.cpp
  Drakhtar/Scenes/RecruitScene.cpp
  Drakhtar/Structures/Font.cpp
  Drakhtar/Structures/Font.h
  Drakhtar/Structures/Texture.cpp
  Drakhtar/Structures/Texture.h
  Drakhtar/Structures/Tween.cpp
Labels: t: bugfix, t: build

#144 Font-NewMenuDesign
  Drakhtar/EventListeners/StoreListener.cpp
  Drakhtar/GameObjects/TutorialBox.cpp
  Drakhtar/Scenes/MenuScene.cpp
  Drakhtar/Structures/Game.cpp
  fonts/Greenscr.ttf
  images/Logos/Logo.png
  images/Logos/Logo2.png
  images/Logos/VG.jpg
  images/Maps/FirstBattle.png
Labels: m: art

#140 Resize sprites and adjust board accordingly
  Drakhtar/GameObjects/Commanders/RedValar.cpp
  Drakhtar/GameObjects/Commanders/Thassa.cpp
  Drakhtar/GameObjects/Commanders/Valar.cpp
  Drakhtar/GameObjects/GameOverPanel.cpp
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/Managers/GameManager.cpp
  Drakhtar/Scenes/GameScene.cpp
  images/Maps/SecondBattle.png
  images/Units/Abeizhul.png
  images/Units/BlueArcher.png
  images/Units/BlueMage.png
  images/Units/BlueMonster.png
  images/Units/BlueSoldier.png
  images/Units/BlueValar.png
  images/Units/RedArcher.png
  images/Units/RedMage.png
  images/Units/RedMonster.png
  images/Units/RedSoldier.png
  images/Units/RedValar.png
  images/Units/Sheissah.png
  images/Units/Thassa.png
  images/Units/Zamdran.png
  levels/level-2.txt
  levels/level-4.txt
  levels/level-5.txt
Labels: m: art, t: bugfix

#145 Removed scene from skills
  Drakhtar/GameObjects/Commanders/Commander.cpp
  Drakhtar/GameObjects/Skill.cpp
  Drakhtar/GameObjects/Skill.h
  Drakhtar/GameObjects/SkillButton.cpp
  Drakhtar/GameObjects/UnitDescriptionBox.cpp
Labels: m: enhancement

#146 Starting gold
  Drakhtar/GameObjects/TutorialBox.cpp
  Drakhtar/Managers/GameManager.h
  Drakhtar/Utils/Constants.h
  tutorials/tutorials.txt
Labels: m: enhancement, t: bugfix

#147 Narrative and credits scene
  Drakhtar/GameObjects/CreditText.cpp
  Drakhtar/GameObjects/CreditText.h
  Drakhtar/GameObjects/DialogScene.cpp
  Drakhtar/GameObjects/GameOverPanel.cpp
  Drakhtar/Scenes/CreditsScene.cpp
  Drakhtar/Scenes/CreditsScene.h
  Drakhtar/Scenes/RecruitScene.cpp
  Drakhtar/Structures/Game.cpp
  dialog/dialog2.txt
  dialog/dialog2transition.txt
  dialog/dialog3.txt
  dialog/dialog3transition.txt
  dialog/dialog4.txt
  dialog/dialog4transition.txt
  dialog/dialog5.txt
  dialog/dialog5transition.txt
  dialog/dialog6transition.txt
  levels/credits.txt
Labels: t: bugfix, t: feature

#149 Recruitment after level 1 and level 2 error
  Drakhtar/GameObjects/DialogScene.cpp
  Drakhtar/Scenes/RecruitScene.cpp
  dialog/dialog3transition.txt
Labels: t: bugfix

#150 KangarooRemoved
  Drakhtar/Structures/Game.cpp
  images/Units/BlueValar.png
Labels: m: art, t: bugfix

#151 Transparent bug fixed
  Drakhtar/GameObjects/TutorialText.cpp
Labels: t: bugfix

#155 rendering order
  Drakhtar/GameObjects/Unit.cpp
  Drakhtar/GameObjects/Unit.h
  Drakhtar/Managers/GameManager.cpp
  Drakhtar/Scenes/GameScene.cpp
  Drakhtar/Scenes/GameScene.h
  levels/level-1.txt
Labels: m: bug, s: wontfix, t: bugfix

#153 AIController for the enemy team
  Drakhtar/Controllers/AIController.cpp
  Drakhtar/Controllers/AIController.h
  Drakhtar/Controllers/PlayerController.cpp
  Drakhtar/Controllers/PlayerController.h
  Drakhtar/Controllers/UnitsController.cpp
  Drakhtar/Controllers/UnitsController.h
  Drakhtar/Scenes/GameScene.cpp
Labels: t: feature
